### PR TITLE
Fixed creating PDSE [WIP]

### PR DESCRIPTION
**Pull request by temanbrcom**
Fixed creating of PDSE data sets by mapping the "dsorg" parameter of a request from PO_E to PO and setting "dsntype=LIBRARY". 
For more details please see: https://github.com/zowe/data-sets/issues/113

Signed-off-by: temanbrcom <andrei.temnikov@broadcom.com>

### CODE REVIEW

**Comment by temanbrcom** [comment]
I agree, will do

**Comment by temanbrcom** [comment]
@stevenhorsman I have added integration tests. Please, could you review them?

**Comment by stevenhorsman** [comment]
Looks good - thanks Andrei!

**Comment by temanbrcom** [comment]
Thank you, Steven!

**Pull request merged**
